export const dbMap = {
  // Módulo 1 - Consumos y Medios
  "mod1-1": "Formato: Cortos vs Largos", 
  "mod1-2": "Modo avión (Estudio)",
  "mod1-22": "Horas en Redes Sociales",
  "mod1-3": "Cine (Voracidad)",
  "mod1-4": "Libros (Voracidad)",
  "mod1-5": "Podcasts (Voracidad)",
  "mod1-6": "Música (Voracidad)",
  "mod1-7": "Videojuegos (Voracidad)",
  "mod1-8": "Diseño IG (Voracidad)",
  "mod1-9": "Diversidad Cultural",
  "mod1-10": "Horas: YouTube",
  "mod1-11": "Horas: Spotify",
  "mod1-12": "Horas: HBO",
  "mod1-13": "Horas: Netflix",
  "mod1-14": "Horas: Stremio",
  "mod1-15": "Horas: TikTok",
  "mod1-16": "Horas: Disney",
  "mod1-17": "Horas: Twitch",
  "mod1-18": "Horas: Mubi",
  "mod1-19": "Horas: Instagram",
  "mod1-20": "Horas: Amazon",
  "mod1-21": "Horas: Kick",
  "mod1-23": "Frecuencia uso Referencias",
  "mod1-24": "Importancia de Referencias",

  // Módulo 2 - Forma de Trabajar
  "mod2-1": "Boceto a mano",
  "mod2-2": "Perfeccionismo",
  "mod2-3": "Procrastinacion",
  "mod2-4": "Silencio para trabajar",
  "mod2-5": "Pausas programadas",
  "mod2-6": "Setup escritorio",
  "mod2-7": "Trabajo nocturno",
  "mod2-8": "Respaldo nube",
  "mod2-9": "Programas simultáneos",
  "mod2-10": "Pestañas abiertas",
  "mod2-11": "Archivos sin título",
  "mod2-12": "Versiones vs Sobrescribir",
  "mod2-13": "Notificaciones activadas",
  "mod2-14": "Comer escritorio",
  "mod2-15": "Interrupciones",
  "mod2-16": "Sindrome impostor",
  "mod2-17": "Orden archivos",

  // Módulo 3 - Ansiedad y Estrés
  "mod3-1": "Trabajo bajo presión",
  "mod3-2": "Confianza en decisiones",
  "mod3-3": "Planificación vs último momento",
  "mod3-4": "Comparacion con otros",
  "mod3-5": "Emocion dominante",
  "mod3-6": "Horas sueno habituales",
  "mod3-7": "Horas sueno pre entrega",
  "mod3-8": "Procrastinas",
  "mod3-9": "Proc: Redes",
  "mod3-10": "Proc: Ordenar",
  "mod3-11": "Proc: Gym",
  "mod3-12": "Proc: Dormir",
  "mod3-13": "Proc: Otras Tareas",
  "mod3-14": "Proc: Otros",
  "mod3-15": "Momento mayor frustracion",
  "mod3-16": "Nivel de ansiedad general",
  "mod3-17": "Emociones afectan resultado",
  "mod3-18": "Tecnicas de concentracion",
  "mod3-19": "Sintomas fisicos",

  // Consola / Demografía
  "demo-age": "Filtro: Edad",
  "demo-gender": "Filtro: Género",
  "demo-career": "Filtro: Carrera",
  "demo-xp": "Filtro: Años de experiencia",
  "demo-work": "Filtro: Trabajo",
  "demo-hours": "Filtro: Horas de trabajo",
  "demo-modality": "Filtro: Modalidad de trabajo",
  "demo-avg": "Visualizar Promedio",
  "demo-country": "Filtro: País",
  "demo-travel": "Filtro: Tiempo de Viaje",
  "demo-living": "Filtro: Convivencia"
};

export const reverseDbMap = Object.entries(dbMap).reduce((acc, [compId, dbKey]) => {
  acc[dbKey] = compId;
  return acc;
}, {});
